-- Enriched country catalogue — full ISO 3166-1 alpha-3 list
-- 248 countries, 92 attested in CTDC

SET search_path TO ramona, public;
ALTER TABLE ramona.countries ADD COLUMN IF NOT EXISTS country_iso3 TEXT;
ALTER TABLE ramona.countries ADD COLUMN IF NOT EXISTS country_name_es TEXT;
ALTER TABLE ramona.countries ADD COLUMN IF NOT EXISTS attested_in_ctdc BOOLEAN NOT NULL DEFAULT FALSE;

INSERT INTO countries (country_code, country_name, country_iso3, country_name_es, attested_in_ctdc) VALUES
  ('AB', 'Aruba', 'ABW', 'Aruba', FALSE),
  ('AF', 'Afghanistan', 'AFG', 'Afganistán', TRUE),
  ('AG', 'Angola', 'AGO', 'Angola', FALSE),
  ('AI', 'Anguilla', 'AIA', 'Anguila', FALSE),
  ('AL', 'Åland Islands', 'ALA', 'Islas Åland', FALSE),
  ('AL', 'Albania', 'ALB', 'Albania', TRUE),
  ('AN', 'Andorra', 'AND', 'Andorra', FALSE),
  ('AR', 'United Arab Emirates', 'ARE', 'Emiratos Árabes Unidos', TRUE),
  ('AR', 'Argentina', 'ARG', 'Argentina', TRUE),
  ('AR', 'Armenia', 'ARM', 'Armenia', FALSE),
  ('AS', 'American Samoa', 'ASM', 'Samoa Americana', FALSE),
  ('AT', 'Antarctica', 'ATA', 'Antártida', FALSE),
  ('AT', 'Antigua and Barbuda', 'ATG', 'Antigua y Barbuda', FALSE),
  ('AU', 'Australia', 'AUS', 'Australia', FALSE),
  ('AU', 'Austria', 'AUT', 'Austria', FALSE),
  ('AZ', 'Azerbaijan', 'AZE', 'Azerbaiyán', FALSE),
  ('BD', 'Burundi', 'BDI', 'Burundi', TRUE),
  ('BE', 'Belgium', 'BEL', 'Bélgica', FALSE),
  ('BE', 'Benin', 'BEN', 'Benín', FALSE),
  ('BE', 'Bonaire', 'BES', 'Bonaire', FALSE),
  ('BF', 'Burkina Faso', 'BFA', 'Burkina Faso', FALSE),
  ('BG', 'Bangladesh', 'BGD', 'Bangladesh', TRUE),
  ('BG', 'Bulgaria', 'BGR', 'Bulgaria', TRUE),
  ('BH', 'Bahrain', 'BHR', 'Baréin', FALSE),
  ('BH', 'Bahamas', 'BHS', 'Bahamas', FALSE),
  ('BI', 'Bosnia and Herzegovina', 'BIH', 'Bosnia y Herzegovina', TRUE),
  ('BL', 'Saint Barthélemy', 'BLM', 'San Bartolomé', FALSE),
  ('BL', 'Belarus', 'BLR', 'Bielorrusia', TRUE),
  ('BL', 'Belize', 'BLZ', 'Belice', FALSE),
  ('BM', 'Bermuda', 'BMU', 'Bermudas', FALSE),
  ('BO', 'Bolivia', 'BOL', 'Bolivia', TRUE),
  ('BR', 'Brazil', 'BRA', 'Brasil', TRUE),
  ('BR', 'Barbados', 'BRB', 'Barbados', FALSE),
  ('BR', 'Brunei', 'BRN', 'Brunéi', FALSE),
  ('BT', 'Bhutan', 'BTN', 'Bután', FALSE),
  ('BV', 'Bouvet Island', 'BVT', 'Isla Bouvet', FALSE),
  ('BW', 'Botswana', 'BWA', 'Botsuana', FALSE),
  ('CA', 'Central African Republic', 'CAF', 'República Centroafricana', FALSE),
  ('CA', 'Canada', 'CAN', 'Canadá', TRUE),
  ('CC', 'Cocos Islands', 'CCK', 'Islas Cocos', FALSE),
  ('CH', 'Switzerland', 'CHE', 'Suiza', TRUE),
  ('CH', 'Chile', 'CHL', 'Chile', FALSE),
  ('CH', 'China', 'CHN', 'China', TRUE),
  ('CI', 'Côte d''Ivoire', 'CIV', 'Costa de Marfil', TRUE),
  ('CM', 'Cameroon', 'CMR', 'Camerún', TRUE),
  ('CO', 'DR Congo', 'COD', 'RD del Congo', TRUE),
  ('CO', 'Congo', 'COG', 'Congo', FALSE),
  ('CO', 'Cook Islands', 'COK', 'Islas Cook', FALSE),
  ('CO', 'Colombia', 'COL', 'Colombia', TRUE),
  ('CO', 'Comoros', 'COM', 'Comoras', FALSE),
  ('CP', 'Cape Verde', 'CPV', 'Cabo Verde', FALSE),
  ('CR', 'Costa Rica', 'CRI', 'Costa Rica', FALSE),
  ('CU', 'Cuba', 'CUB', 'Cuba', TRUE),
  ('CU', 'Curaçao', 'CUW', 'Curazao', FALSE),
  ('CX', 'Christmas Island', 'CXR', 'Isla de Navidad', FALSE),
  ('CY', 'Cayman Islands', 'CYM', 'Islas Caimán', FALSE),
  ('CY', 'Cyprus', 'CYP', 'Chipre', FALSE),
  ('CZ', 'Czechia', 'CZE', 'Chequia', TRUE),
  ('DE', 'Germany', 'DEU', 'Alemania', TRUE),
  ('DJ', 'Djibouti', 'DJI', 'Yibuti', FALSE),
  ('DM', 'Dominica', 'DMA', 'Dominica', FALSE),
  ('DN', 'Denmark', 'DNK', 'Dinamarca', TRUE),
  ('DO', 'Dominican Republic', 'DOM', 'República Dominicana', TRUE),
  ('DZ', 'Algeria', 'DZA', 'Argelia', FALSE),
  ('EC', 'Ecuador', 'ECU', 'Ecuador', FALSE),
  ('EG', 'Egypt', 'EGY', 'Egipto', TRUE),
  ('ER', 'Eritrea', 'ERI', 'Eritrea', TRUE),
  ('ES', 'Western Sahara', 'ESH', 'Sahara Occidental', FALSE),
  ('ES', 'Spain', 'ESP', 'España', TRUE),
  ('ES', 'Estonia', 'EST', 'Estonia', FALSE),
  ('ET', 'Ethiopia', 'ETH', 'Etiopía', TRUE),
  ('FI', 'Finland', 'FIN', 'Finlandia', FALSE),
  ('FJ', 'Fiji', 'FJI', 'Fiyi', FALSE),
  ('FL', 'Falkland Islands', 'FLK', 'Islas Malvinas', FALSE),
  ('FR', 'France', 'FRA', 'Francia', FALSE),
  ('FR', 'Faroe Islands', 'FRO', 'Islas Feroe', FALSE),
  ('FS', 'Micronesia', 'FSM', 'Micronesia', FALSE),
  ('GA', 'Gabon', 'GAB', 'Gabón', FALSE),
  ('GB', 'United Kingdom', 'GBR', 'Reino Unido', TRUE),
  ('GE', 'Georgia', 'GEO', 'Georgia', FALSE),
  ('GG', 'Guernsey', 'GGY', 'Guernsey', FALSE),
  ('GH', 'Ghana', 'GHA', 'Ghana', TRUE),
  ('GI', 'Gibraltar', 'GIB', 'Gibraltar', FALSE),
  ('GI', 'Guinea', 'GIN', 'Guinea', TRUE),
  ('GL', 'Guadeloupe', 'GLP', 'Guadalupe', FALSE),
  ('GM', 'Gambia', 'GMB', 'Gambia', FALSE),
  ('GN', 'Guinea-Bissau', 'GNB', 'Guinea-Bisáu', FALSE),
  ('GN', 'Equatorial Guinea', 'GNQ', 'Guinea Ecuatorial', FALSE),
  ('GR', 'Greece', 'GRC', 'Grecia', TRUE),
  ('GR', 'Grenada', 'GRD', 'Granada', FALSE),
  ('GR', 'Greenland', 'GRL', 'Groenlandia', FALSE),
  ('GT', 'Guatemala', 'GTM', 'Guatemala', TRUE),
  ('GU', 'French Guiana', 'GUF', 'Guayana Francesa', FALSE),
  ('GU', 'Guam', 'GUM', 'Guam', FALSE),
  ('GU', 'Guyana', 'GUY', 'Guyana', FALSE),
  ('HK', 'Hong Kong', 'HKG', 'Hong Kong', TRUE),
  ('HM', 'Heard and McDonald Islands', 'HMD', 'Islas Heard y McDonald', FALSE),
  ('HN', 'Honduras', 'HND', 'Honduras', TRUE),
  ('HR', 'Croatia', 'HRV', 'Croacia', FALSE),
  ('HT', 'Haiti', 'HTI', 'Haití', TRUE),
  ('HU', 'Hungary', 'HUN', 'Hungría', TRUE),
  ('ID', 'Indonesia', 'IDN', 'Indonesia', TRUE),
  ('IM', 'Isle of Man', 'IMN', 'Isla de Man', FALSE),
  ('IN', 'India', 'IND', 'India', TRUE),
  ('IO', 'British Indian Ocean Territory', 'IOT', 'Territorio Británico del Océano Índico', FALSE),
  ('IR', 'Ireland', 'IRL', 'Irlanda', FALSE),
  ('IR', 'Iran', 'IRN', 'Irán', FALSE),
  ('IR', 'Iraq', 'IRQ', 'Irak', TRUE),
  ('IS', 'Iceland', 'ISL', 'Islandia', FALSE),
  ('IS', 'Israel', 'ISR', 'Israel', FALSE),
  ('IT', 'Italy', 'ITA', 'Italia', TRUE),
  ('JA', 'Jamaica', 'JAM', 'Jamaica', TRUE),
  ('JE', 'Jersey', 'JEY', 'Jersey', FALSE),
  ('JO', 'Jordan', 'JOR', 'Jordania', TRUE),
  ('JP', 'Japan', 'JPN', 'Japón', TRUE),
  ('KA', 'Kazakhstan', 'KAZ', 'Kazajistán', TRUE),
  ('KE', 'Kenya', 'KEN', 'Kenia', TRUE),
  ('KG', 'Kyrgyzstan', 'KGZ', 'Kirguistán', TRUE),
  ('KH', 'Cambodia', 'KHM', 'Camboya', TRUE),
  ('KI', 'Kiribati', 'KIR', 'Kiribati', FALSE),
  ('KN', 'Saint Kitts and Nevis', 'KNA', 'San Cristóbal y Nieves', FALSE),
  ('KO', 'South Korea', 'KOR', 'Corea del Sur', TRUE),
  ('KW', 'Kuwait', 'KWT', 'Kuwait', TRUE),
  ('LA', 'Laos', 'LAO', 'Laos', TRUE),
  ('LB', 'Lebanon', 'LBN', 'Líbano', TRUE),
  ('LB', 'Liberia', 'LBR', 'Liberia', FALSE),
  ('LB', 'Libya', 'LBY', 'Libia', TRUE),
  ('LC', 'Saint Lucia', 'LCA', 'Santa Lucía', FALSE),
  ('LI', 'Liechtenstein', 'LIE', 'Liechtenstein', FALSE),
  ('LK', 'Sri Lanka', 'LKA', 'Sri Lanka', TRUE),
  ('LS', 'Lesotho', 'LSO', 'Lesoto', FALSE),
  ('LT', 'Lithuania', 'LTU', 'Lituania', FALSE),
  ('LU', 'Luxembourg', 'LUX', 'Luxemburgo', FALSE),
  ('LV', 'Latvia', 'LVA', 'Letonia', FALSE),
  ('MA', 'Macau', 'MAC', 'Macao', FALSE),
  ('MA', 'Saint Martin (French)', 'MAF', 'San Martín (francesa)', FALSE),
  ('MA', 'Morocco', 'MAR', 'Marruecos', TRUE),
  ('MC', 'Monaco', 'MCO', 'Mónaco', FALSE),
  ('MD', 'Moldova', 'MDA', 'Moldavia', TRUE),
  ('MD', 'Madagascar', 'MDG', 'Madagascar', TRUE),
  ('MD', 'Maldives', 'MDV', 'Maldivas', FALSE),
  ('ME', 'Mexico', 'MEX', 'México', TRUE),
  ('MH', 'Marshall Islands', 'MHL', 'Islas Marshall', FALSE),
  ('MK', 'North Macedonia', 'MKD', 'Macedonia del Norte', TRUE),
  ('ML', 'Mali', 'MLI', 'Malí', TRUE),
  ('ML', 'Malta', 'MLT', 'Malta', FALSE),
  ('MM', 'Myanmar', 'MMR', 'Myanmar', TRUE),
  ('MN', 'Montenegro', 'MNE', 'Montenegro', FALSE),
  ('MN', 'Mongolia', 'MNG', 'Mongolia', FALSE),
  ('MN', 'Northern Mariana Islands', 'MNP', 'Islas Marianas del Norte', FALSE),
  ('MO', 'Mozambique', 'MOZ', 'Mozambique', FALSE),
  ('MR', 'Mauritania', 'MRT', 'Mauritania', FALSE),
  ('MS', 'Montserrat', 'MSR', 'Montserrat', FALSE),
  ('MT', 'Martinique', 'MTQ', 'Martinica', FALSE),
  ('MU', 'Mauritius', 'MUS', 'Mauricio', FALSE),
  ('MW', 'Malawi', 'MWI', 'Malaui', FALSE),
  ('MY', 'Malaysia', 'MYS', 'Malasia', TRUE),
  ('MY', 'Mayotte', 'MYT', 'Mayotte', FALSE),
  ('NA', 'Namibia', 'NAM', 'Namibia', FALSE),
  ('NC', 'New Caledonia', 'NCL', 'Nueva Caledonia', FALSE),
  ('NE', 'Niger', 'NER', 'Níger', TRUE),
  ('NF', 'Norfolk Island', 'NFK', 'Isla Norfolk', FALSE),
  ('NG', 'Nigeria', 'NGA', 'Nigeria', TRUE),
  ('NI', 'Nicaragua', 'NIC', 'Nicaragua', FALSE),
  ('NI', 'Niue', 'NIU', 'Niue', FALSE),
  ('NL', 'Netherlands', 'NLD', 'Países Bajos', TRUE),
  ('NO', 'Norway', 'NOR', 'Noruega', FALSE),
  ('NP', 'Nepal', 'NPL', 'Nepal', TRUE),
  ('NR', 'Nauru', 'NRU', 'Nauru', FALSE),
  ('NZ', 'New Zealand', 'NZL', 'Nueva Zelanda', FALSE),
  ('OM', 'Oman', 'OMN', 'Omán', TRUE),
  ('PA', 'Pakistan', 'PAK', 'Pakistán', FALSE),
  ('PA', 'Panama', 'PAN', 'Panamá', FALSE),
  ('PC', 'Pitcairn', 'PCN', 'Pitcairn', FALSE),
  ('PE', 'Peru', 'PER', 'Perú', FALSE),
  ('PH', 'Philippines', 'PHL', 'Filipinas', TRUE),
  ('PL', 'Palau', 'PLW', 'Palaos', FALSE),
  ('PN', 'Papua New Guinea', 'PNG', 'Papúa Nueva Guinea', FALSE),
  ('PO', 'Poland', 'POL', 'Polonia', TRUE),
  ('PR', 'Puerto Rico', 'PRI', 'Puerto Rico', FALSE),
  ('PR', 'North Korea', 'PRK', 'Corea del Norte', FALSE),
  ('PR', 'Portugal', 'PRT', 'Portugal', TRUE),
  ('PR', 'Paraguay', 'PRY', 'Paraguay', FALSE),
  ('PS', 'Palestine', 'PSE', 'Palestina', FALSE),
  ('PY', 'French Polynesia', 'PYF', 'Polinesia Francesa', FALSE),
  ('QA', 'Qatar', 'QAT', 'Catar', TRUE),
  ('RE', 'Réunion', 'REU', 'Reunión', FALSE),
  ('RO', 'Romania', 'ROU', 'Rumania', TRUE),
  ('RU', 'Russia', 'RUS', 'Rusia', TRUE),
  ('RW', 'Rwanda', 'RWA', 'Ruanda', FALSE),
  ('SA', 'Saudi Arabia', 'SAU', 'Arabia Saudita', TRUE),
  ('SD', 'Sudan', 'SDN', 'Sudán', TRUE),
  ('SE', 'Senegal', 'SEN', 'Senegal', TRUE),
  ('SG', 'Singapore', 'SGP', 'Singapur', FALSE),
  ('SG', 'South Georgia', 'SGS', 'Georgia del Sur', FALSE),
  ('SH', 'Saint Helena', 'SHN', 'Santa Helena', FALSE),
  ('SJ', 'Svalbard and Jan Mayen', 'SJM', 'Svalbard y Jan Mayen', FALSE),
  ('SL', 'Solomon Islands', 'SLB', 'Islas Salomón', FALSE),
  ('SL', 'Sierra Leone', 'SLE', 'Sierra Leona', TRUE),
  ('SL', 'El Salvador', 'SLV', 'El Salvador', TRUE),
  ('SM', 'San Marino', 'SMR', 'San Marino', FALSE),
  ('SO', 'Somalia', 'SOM', 'Somalia', TRUE),
  ('SP', 'Saint Pierre and Miquelon', 'SPM', 'San Pedro y Miquelón', FALSE),
  ('SR', 'Serbia', 'SRB', 'Serbia', TRUE),
  ('SS', 'South Sudan', 'SSD', 'Sudán del Sur', FALSE),
  ('ST', 'São Tomé and Príncipe', 'STP', 'Santo Tomé y Príncipe', FALSE),
  ('SU', 'Suriname', 'SUR', 'Surinam', FALSE),
  ('SV', 'Slovakia', 'SVK', 'Eslovaquia', FALSE),
  ('SV', 'Slovenia', 'SVN', 'Eslovenia', FALSE),
  ('SW', 'Sweden', 'SWE', 'Suecia', TRUE),
  ('SW', 'Eswatini', 'SWZ', 'Esuatini', FALSE),
  ('SX', 'Sint Maarten', 'SXM', 'San Martín (neerlandesa)', FALSE),
  ('SY', 'Seychelles', 'SYC', 'Seychelles', FALSE),
  ('SY', 'Syria', 'SYR', 'Siria', FALSE),
  ('TC', 'Turks and Caicos Islands', 'TCA', 'Islas Turcas y Caicos', FALSE),
  ('TC', 'Chad', 'TCD', 'Chad', FALSE),
  ('TG', 'Togo', 'TGO', 'Togo', FALSE),
  ('TH', 'Thailand', 'THA', 'Tailandia', TRUE),
  ('TJ', 'Tajikistan', 'TJK', 'Tayikistán', TRUE),
  ('TK', 'Tokelau', 'TKL', 'Tokelau', FALSE),
  ('TK', 'Turkmenistan', 'TKM', 'Turkmenistán', TRUE),
  ('TL', 'Timor-Leste', 'TLS', 'Timor Oriental', FALSE),
  ('TO', 'Tonga', 'TON', 'Tonga', FALSE),
  ('TT', 'Trinidad and Tobago', 'TTO', 'Trinidad y Tobago', FALSE),
  ('TU', 'Tunisia', 'TUN', 'Túnez', TRUE),
  ('TU', 'Turkey', 'TUR', 'Turquía', TRUE),
  ('TU', 'Tuvalu', 'TUV', 'Tuvalu', FALSE),
  ('TW', 'Taiwan', 'TWN', 'Taiwán', FALSE),
  ('TZ', 'Tanzania', 'TZA', 'Tanzania', FALSE),
  ('UG', 'Uganda', 'UGA', 'Uganda', TRUE),
  ('UK', 'Ukraine', 'UKR', 'Ucrania', TRUE),
  ('UM', 'U.S. Minor Outlying Islands', 'UMI', 'Islas menores de EE.UU.', FALSE),
  ('UR', 'Uruguay', 'URY', 'Uruguay', FALSE),
  ('US', 'United States', 'USA', 'Estados Unidos', TRUE),
  ('UZ', 'Uzbekistan', 'UZB', 'Uzbekistán', TRUE),
  ('VA', 'Holy See', 'VAT', 'Ciudad del Vaticano', FALSE),
  ('VC', 'Saint Vincent and the Grenadines', 'VCT', 'San Vicente y las Granadinas', FALSE),
  ('VE', 'Venezuela', 'VEN', 'Venezuela', TRUE),
  ('VG', 'British Virgin Islands', 'VGB', 'Islas Vírgenes Británicas', FALSE),
  ('VI', 'U.S. Virgin Islands', 'VIR', 'Islas Vírgenes Americanas', FALSE),
  ('VN', 'Vietnam', 'VNM', 'Vietnam', TRUE),
  ('VU', 'Vanuatu', 'VUT', 'Vanuatu', FALSE),
  ('WL', 'Wallis and Futuna', 'WLF', 'Wallis y Futuna', FALSE),
  ('WS', 'Samoa', 'WSM', 'Samoa', FALSE),
  ('YE', 'Yemen', 'YEM', 'Yemen', FALSE),
  ('ZA', 'South Africa', 'ZAF', 'Sudáfrica', TRUE),
  ('ZM', 'Zambia', 'ZMB', 'Zambia', FALSE),
  ('ZW', 'Zimbabwe', 'ZWE', 'Zimbabue', FALSE)
ON CONFLICT (country_code) DO UPDATE SET
  country_iso3 = EXCLUDED.country_iso3,
  country_name_es = EXCLUDED.country_name_es,
  attested_in_ctdc = EXCLUDED.attested_in_ctdc;