-- Enriched country catalogue
-- 92 ISO3 codes attested in the CTDC Global Synthetic Dataset v2025

SET search_path TO ramona, public;

-- Ensure the ISO3 column exists
ALTER TABLE ramona.countries ADD COLUMN IF NOT EXISTS country_iso3 TEXT;
ALTER TABLE ramona.countries ADD COLUMN IF NOT EXISTS country_name_es TEXT;

INSERT INTO countries (country_code, country_name, country_iso3, country_name_es) VALUES
  ('AF', 'Afghanistan', 'AFG', 'Afganistán'),
  ('AL', 'Albania', 'ALB', 'Albania'),
  ('AR', 'United Arab Emirates', 'ARE', 'Emiratos Árabes Unidos'),
  ('AR', 'Argentina', 'ARG', 'Argentina'),
  ('BD', 'Burundi', 'BDI', 'Burundi'),
  ('BG', 'Bangladesh', 'BGD', 'Bangladesh'),
  ('BG', 'Bulgaria', 'BGR', 'Bulgaria'),
  ('BI', 'Bosnia and Herzegovina', 'BIH', 'Bosnia y Herzegovina'),
  ('BL', 'Belarus', 'BLR', 'Bielorrusia'),
  ('BO', 'Bolivia', 'BOL', 'Bolivia'),
  ('BR', 'Brazil', 'BRA', 'Brasil'),
  ('CA', 'Canada', 'CAN', 'Canadá'),
  ('CH', 'Switzerland', 'CHE', 'Suiza'),
  ('CH', 'China', 'CHN', 'China'),
  ('CI', 'Côte d''Ivoire', 'CIV', 'Costa de Marfil'),
  ('CM', 'Cameroon', 'CMR', 'Camerún'),
  ('CO', 'DR Congo', 'COD', 'RD del Congo'),
  ('CO', 'Colombia', 'COL', 'Colombia'),
  ('CU', 'Cuba', 'CUB', 'Cuba'),
  ('CZ', 'Czechia', 'CZE', 'Chequia'),
  ('DE', 'Germany', 'DEU', 'Alemania'),
  ('DN', 'Denmark', 'DNK', 'Dinamarca'),
  ('DO', 'Dominican Republic', 'DOM', 'República Dominicana'),
  ('EG', 'Egypt', 'EGY', 'Egipto'),
  ('ER', 'Eritrea', 'ERI', 'Eritrea'),
  ('ES', 'Spain', 'ESP', 'España'),
  ('ET', 'Ethiopia', 'ETH', 'Etiopía'),
  ('GB', 'United Kingdom', 'GBR', 'Reino Unido'),
  ('GH', 'Ghana', 'GHA', 'Ghana'),
  ('GI', 'Guinea', 'GIN', 'Guinea'),
  ('GR', 'Greece', 'GRC', 'Grecia'),
  ('GT', 'Guatemala', 'GTM', 'Guatemala'),
  ('HK', 'HKG', 'HKG', 'HKG'),
  ('HN', 'Honduras', 'HND', 'Honduras'),
  ('HT', 'Haiti', 'HTI', 'Haití'),
  ('HU', 'Hungary', 'HUN', 'Hungría'),
  ('ID', 'Indonesia', 'IDN', 'Indonesia'),
  ('IN', 'India', 'IND', 'India'),
  ('IR', 'Iraq', 'IRQ', 'Irak'),
  ('IT', 'Italy', 'ITA', 'Italia'),
  ('JA', 'Jamaica', 'JAM', 'Jamaica'),
  ('JO', 'Jordan', 'JOR', 'Jordania'),
  ('JP', 'Japan', 'JPN', 'Japón'),
  ('KA', 'Kazakhstan', 'KAZ', 'Kazajistán'),
  ('KE', 'Kenya', 'KEN', 'Kenia'),
  ('KG', 'Kyrgyzstan', 'KGZ', 'Kirguistán'),
  ('KH', 'Cambodia', 'KHM', 'Camboya'),
  ('KO', 'South Korea', 'KOR', 'Corea del Sur'),
  ('KW', 'Kuwait', 'KWT', 'Kuwait'),
  ('LA', 'Laos', 'LAO', 'Laos'),
  ('LB', 'Lebanon', 'LBN', 'Líbano'),
  ('LB', 'Libya', 'LBY', 'Libia'),
  ('LK', 'Sri Lanka', 'LKA', 'Sri Lanka'),
  ('MA', 'Morocco', 'MAR', 'Marruecos'),
  ('MD', 'Moldova', 'MDA', 'Moldavia'),
  ('MD', 'Madagascar', 'MDG', 'Madagascar'),
  ('ME', 'Mexico', 'MEX', 'México'),
  ('MK', 'North Macedonia', 'MKD', 'Macedonia del Norte'),
  ('ML', 'Mali', 'MLI', 'Malí'),
  ('MM', 'Myanmar', 'MMR', 'Myanmar'),
  ('MY', 'Malaysia', 'MYS', 'Malasia'),
  ('NE', 'Niger', 'NER', 'Níger'),
  ('NG', 'Nigeria', 'NGA', 'Nigeria'),
  ('NL', 'Netherlands', 'NLD', 'Países Bajos'),
  ('NP', 'Nepal', 'NPL', 'Nepal'),
  ('OM', 'Oman', 'OMN', 'Omán'),
  ('PH', 'Philippines', 'PHL', 'Filipinas'),
  ('PO', 'Poland', 'POL', 'Polonia'),
  ('PR', 'Portugal', 'PRT', 'Portugal'),
  ('QA', 'Qatar', 'QAT', 'Catar'),
  ('RO', 'Romania', 'ROU', 'Rumania'),
  ('RU', 'Russia', 'RUS', 'Rusia'),
  ('SA', 'Saudi Arabia', 'SAU', 'Arabia Saudita'),
  ('SD', 'Sudan', 'SDN', 'Sudán'),
  ('SE', 'Senegal', 'SEN', 'Senegal'),
  ('SL', 'Sierra Leone', 'SLE', 'Sierra Leona'),
  ('SL', 'El Salvador', 'SLV', 'El Salvador'),
  ('SO', 'Somalia', 'SOM', 'Somalia'),
  ('SR', 'Serbia', 'SRB', 'Serbia'),
  ('SW', 'Sweden', 'SWE', 'Suecia'),
  ('TH', 'Thailand', 'THA', 'Tailandia'),
  ('TJ', 'Tajikistan', 'TJK', 'Tayikistán'),
  ('TK', 'Turkmenistan', 'TKM', 'Turkmenistán'),
  ('TU', 'Tunisia', 'TUN', 'Túnez'),
  ('TU', 'Turkey', 'TUR', 'Turquía'),
  ('UG', 'Uganda', 'UGA', 'Uganda'),
  ('UK', 'Ukraine', 'UKR', 'Ucrania'),
  ('US', 'United States', 'USA', 'Estados Unidos'),
  ('UZ', 'Uzbekistan', 'UZB', 'Uzbekistán'),
  ('VE', 'Venezuela', 'VEN', 'Venezuela'),
  ('VN', 'Vietnam', 'VNM', 'Vietnam'),
  ('ZA', 'South Africa', 'ZAF', 'Sudáfrica')
ON CONFLICT (country_code) DO UPDATE SET
  country_iso3 = EXCLUDED.country_iso3,
  country_name_es = EXCLUDED.country_name_es;