-- FraudScheme exemplars: up to 5 real press articles per scheme
-- Derived from 1332 case-relevant classified press articles

SET search_path TO ramona, public;

-- Table to store examples with attribution
CREATE TABLE IF NOT EXISTS fraudscheme_exemplars (
    exemplar_id   BIGSERIAL PRIMARY KEY,
    scheme_code   TEXT NOT NULL,
    example_rank  SMALLINT NOT NULL,
    title         TEXT NOT NULL,
    outlet        TEXT,
    url           TEXT,
    country       TEXT,
    exploit_hint  TEXT,
    UNIQUE (scheme_code, url)
);

INSERT INTO fraudscheme_exemplars (scheme_code, example_rank, title, outlet, url, country, exploit_hint) VALUES
  ('DebtBondageTraffickingScheme', 1, 'Trata de personas y esclavitud laboral en el Perú: Análisis a propósito del caso Nicolini - Enfoque Derecho', 'Enfoque Derecho', 'https://enfoquederecho.com/trata-de-personas-y-esclavitud-laboral-en-el-peru-analisis-a-proposito-del-caso-nicolini/', 'PER', 'labour_construction'),
  ('DebtBondageTraffickingScheme', 2, 'La trata de personas con fines de explotación sexual expande sus redes en todo México - Desinformémonos', 'Desinformémonos', 'https://desinformemonos.org/la-trata-de-personas-con-fines-de-explotacion-sexual-expande-sus-redes-en-todo-mexico/', 'MEX', 'labour_construction'),
  ('DebtBondageTraffickingScheme', 3, '“México no cumple mínimamente para erradicar la trata de personas”: Departamento de Estado - El Economista', 'El Economista', 'https://www.eleconomista.com.mx/politica/Mexico-no-cumple-minimamente-para-erradicar-la-trata-de-personas-Departamento-de-Estado-20220727-0074.html', 'MEX', 'labour_agriculture'),
  ('DebtBondageTraffickingScheme', 4, 'La trata de personas vulnera la libertad personal; la violación, la libertad sexual; y los delitos de favorecimiento a la prostitución y proxenetismo, la moral sexual de la sociedad y la dignidad de la víctima (doctrina legal) [AP 3-2011/CJ-116, f. j. 12] - LP | Pasión por el Derecho', 'LP | Pasión por el Derecho', 'https://lpderecho.pe/trata-personas-libertad-personal-violacion-libertad-sexual-delitos-favorecimiento-prostitucion-proxenetismo-moral-sexual-sociedad-dignidad-victima-doctrina-legal-ap-3-2011-cj-116-f-j-12/', 'MEX', 'labour_hospitality'),
  ('DebtBondageTraffickingScheme', 5, '30 de Julio: Día Mundial contra la trata de personas - DefensorBA', 'DefensorBA', 'https://www.defensorba.org.ar/contenido/30-de-julio-dia-mundial-contra-la-trata-de-personas', 'ARG', 'labour_hospitality'),
  ('ForcedCriminalityScheme', 1, 'Los otros Izaguirre: el corredor de adiestramiento narco - Connectas', 'Connectas', 'https://www.connectas.org/especiales/rancho-izaguirre-adiestramiento-cartel-jalisco-mexico/', 'MEX', 'labour_hospitality'),
  ('ForcedCriminalityScheme', 2, '"O te matan o te matas": qué se sabe del Rancho Izaguirre un año después del hallazgo en México del lugar de "reclutamiento y exterminio" del cartel CJNG - BBC', 'BBC', 'https://www.bbc.com/mundo/articles/c0mgjngk3ygo', 'MEX', 'labour_construction'),
  ('ForcedCriminalityScheme', 3, 'Videojuegos, trabajos falsos y citas en terminales de autobuses: así recluta el crimen organizado - Milenio', 'Milenio', 'https://www.milenio.com/policia/crimen-organizado-recluta-con-trabajos-falsos-videojuegos-y-citas', 'MEX', 'labour_hospitality'),
  ('ForcedCriminalityScheme', 4, 'Las economías perversas del crimen organizado - Nueva Sociedad', 'Nueva Sociedad', 'https://www.nuso.org/articulo/las-economias-perversas-del-crimen-organizado/imprimir/', 'COL', 'labour_hospitality'),
  ('ForcedCriminalityScheme', 5, 'Crecen desapariciones a través de falsas ofertas de trabajo - Eme Equis', 'Eme Equis', 'https://emeequis.com/investigaciones/crecen-desapariciones-a-traves-de-falsas-ofertas-de-trabajo/', 'MEX', 'labour_construction'),
  ('ForeignLanguageTeacherScheme', 1, 'Alertan de una falsa oferta de empleo del Corte Inglés que ofrece sueldos de hasta 200 euros al día - Levante-EMV', 'Levante-EMV', 'https://www.levante-emv.com/economia/2022/08/23/empleo-el-corte-ingles-estafa-73793446.html', NULL, 'labour_hospitality'),
  ('ForeignLanguageTeacherScheme', 2, 'Nueva estafa de WhatsApp: la supuesta oferta laboral de El Corte Inglés con la que puedes ganar hasta 200 euros al día - ABC', 'ABC', 'https://www.abc.es/tecnologia/nueva-estafa-whatsapp-supuesta-oferta-laboral-corte-20220824203609-nt.html', NULL, NULL),
  ('GigEconomyFakeDriverScheme', 1, 'Prosegur tiene vacantes! La empresa convoca a más de 300 personas con y sin experiencia para diversos cargos como vigilante, portero, atendiente, auxiliar de servicios generales, conductor y muchos otros. - CPG Click Petróleo e Gás', 'CPG Click Petróleo e Gás', 'https://es.clickpetroleoegas.com.br/prosegur-esta-com-vagas-empresa-convoca-mais-de-300-pessoas-com-e-sem-experiencia-em-cargos-diversos-como-vigilante-porteiro-atendente-auxiliar-de-servicos-gerais-motorista-e-muitos-outros/', NULL, 'labour_construction'),
  ('GigEconomyFakeDriverScheme', 2, 'Mundial 2026: El plan de Uber y DiDi para frenar la trata de personas durante el torneo - El Cronista', 'El Cronista', 'https://www.cronista.com/mexico/actualidad-mx/mundial-2026-el-plan-de-uber-y-didi-para-frenar-la-trata-de-personas-durante-el-torneo/', 'MEX', 'labour_hospitality'),
  ('GigEconomyFakeDriverScheme', 3, 'Un youtuber sorprende a sus seguidores al mostrar los vehículos que encontró a la venta en Facebook Marketplace - La Vanguardia', 'La Vanguardia', 'https://www.lavanguardia.com/motor/20241223/10233059/youtuber-sorprende-seguidores-mostrar-vehiculos-encontro-venta-facebook-marketplace-pmv.html', NULL, NULL),
  ('IdentityTheftScheme', 1, 'La trata con fines de explotación laboral en mujeres indígenas en México: una realidad emergente - SciELO México', 'SciELO México', 'https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S2007-55452022000100302', 'MEX', 'labour_agriculture'),
  ('IdentityTheftScheme', 2, 'Víctimas de trata: mujeres migrantes, trabajo agrario y acoso sexual en Tamaulipas - SciELO México', 'SciELO México', 'https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S2007-78582016000200022', 'MEX', 'labour_agriculture'),
  ('IdentityTheftScheme', 3, 'Cómo vender en Facebook Marketplace en 2025: guía para principiantes - Shopify', 'Shopify', 'https://www.shopify.com/es/blog/como-vender-en-facebook-1', 'USA', 'labour_construction'),
  ('IdentityTheftScheme', 4, 'Impunes más del 90% de casos por trata de personas: sin justicia y poco apoyo, las víctimas cargan solas con las secuelas - Infobae', 'Infobae', 'https://www.infobae.com/peru/2025/07/30/impunes-mas-del-90-de-acusados-por-trata-de-personas-sin-justicia-y-poco-apoyo-las-victimas-cargan-solas-con-las-secuelas/', 'MEX', 'labour_construction'),
  ('IdentityTheftScheme', 5, 'Víctimas de trata: seis crudos testimonios de quienes denunciaron explotación - Infobae', 'Infobae', 'https://www.infobae.com/sociedad/policiales/2022/06/26/victimas-de-trata-seis-crudos-testimonios-de-quienes-denunciaron-explotacion/', 'MEX', 'labour_construction'),
  ('InPersonLureScheme', 1, 'Trata y narco: el trasfondo de la desaparición de mujeres en Guerrero - Unidad de Investigaciones Periodísticas UNAM', 'Unidad de Investigaciones Periodísticas UNAM', 'https://corrientealterna.unam.mx/nota/trata-y-narco-el-trasfondo-de-la-desaparicion-de-mujeres-en-guerrero/', 'MEX', 'labour_hospitality'),
  ('InPersonLureScheme', 2, 'Edith Guadalupe: ante dilación y omisiones oficiales, una mamá hace otra vez el trabajo de las autoridades - Grupo Animal', 'Grupo Animal', 'https://grupoanimal.mx/estados/feminicidio-edith-guadalupe-omisiones-autoridades-madre-investiga', 'MEX', 'labour_construction'),
  ('InPersonLureScheme', 3, '¿Qué pasó con Edith Guadalupe? Cronología del caso: salió a buscar trabajo y fue hallada sin vida - Milenio', 'Milenio', 'https://www.milenio.com/policia/caso-edith-guadalupe-valdes-hallada-sin-vida-cdmx-cronologia', 'MEX', 'labour_hospitality'),
  ('InPersonLureScheme', 4, 'Rancho Izaguirre: a un año del hallazgo que exhibió la maquinaria de desapariciones en Jalisco - LJA.MX', 'LJA.MX', 'https://www.lja.mx/2026/03/rancho-izaguirre-a-un-ano-del-hallazgo-que-exhibio-la-maquinaria-de-desapariciones-en-jalisco/', 'MEX', 'labour_hospitality'),
  ('InPersonLureScheme', 5, 'Alertan por posible red de trata tras asesinato de Edith Guadalupe, expone tía - Infobae', 'Infobae', 'https://www.infobae.com/mexico/2026/04/18/alertan-por-posible-red-de-trata-tras-asesinato-de-edith-guadalupe-expone-tia/', 'MEX', 'labour_hospitality'),
  ('OnlineInfluencerSalesScheme', 1, 'Así se maneja el negocio ilegal de las “fiestas sexuales” en Medellín, que son promovidas por ‘influencers’ - Infobae', 'Infobae', 'https://www.infobae.com/colombia/2026/04/18/asi-se-maneja-el-negocio-ilegal-de-las-fiestas-sexuales-en-medellin-que-son-promovidas-por-influencers/', 'COL', 'sex_prostitution'),
  ('OnlineInfluencerSalesScheme', 2, 'Narcoinfluencers: El creciente vínculo entre redes sociales y crimen organizado - Expansión Política', 'Expansión Política', 'https://politica.expansion.mx/mexico/2025/05/19/narcoinfluencers-redes-sociales-y-crimen-organizado', 'MEX', NULL),
  ('OnlineInfluencerSalesScheme', 3, 'Los Influencers de la Guerra: Reclutamiento a menores a través de redes sociales. - Indepaz', 'Indepaz', 'https://indepaz.org.co/los-influencers-de-la-guerra-reclutamiento-a-menores-a-traves-de-redes-sociales/', 'COL', NULL),
  ('OnlineInfluencerSalesScheme', 4, 'Detenido el ‘influencer’ Jaime Toral, acusado por trata de personas en Veracruz - EL PAÍS', 'EL PAÍS', 'https://elpais.com/mexico/2025-12-24/detenido-el-influencer-jaime-toral-acusado-por-trata-de-personas-en-veracruz.html', 'MEX', 'labour_hospitality'),
  ('OnlineInfluencerSalesScheme', 5, 'Jaime Toral, un influencer buscado por la Fiscalía de Veracruz por trata de personas - EL PAÍS', 'EL PAÍS', 'https://elpais.com/mexico/2025-10-30/jaime-toral-un-influencer-buscado-por-la-fiscalia-de-veracruz-por-trata-de-personas.html', NULL, 'labour_hospitality'),
  ('PayToWorkScheme', 1, 'Fraude en ofertas de trabajo: Criminales piden dinero para dar puestos falsos y roban información - El Financiero', 'El Financiero', 'https://www.elfinanciero.com.mx/empresas/2023/01/16/fraude-en-ofertas-de-trabajo-criminales-piden-dinero-para-dar-puestos-falsos-y-roban-informacion/', 'MEX', 'labour_hospitality')
ON CONFLICT (scheme_code, url) DO NOTHING;