-- Deep regex patterns (v1.4)
-- Extracted from full text of 1332 case-relevant press articles

SET search_path TO ramona, public;

INSERT INTO survivor_patterns (pattern_name, pattern_description, pattern_kind, observed_count, dominance_bucket, evidence_source) VALUES
  ('domicilio_en_vivo', 'Patrón narrativo profundo detectado por análisis textual: domicilio en vivo.', 'deep_textual', 221, 'hot', NULL),
  ('usa_nombre_celebridad', 'Patrón narrativo profundo detectado por análisis textual: usa nombre celebridad.', 'deep_textual', 25, 'warm', NULL),
  ('ubicacion_zona_fronteriza', 'Patrón narrativo profundo detectado por análisis textual: ubicacion zona fronteriza.', 'deep_textual', 17, 'warm', NULL),
  ('reclutador_insiste_urgente', 'Patrón narrativo profundo detectado por análisis textual: reclutador insiste urgente.', 'deep_textual', 16, 'warm', NULL),
  ('requisito_estar_soltera', 'Patrón narrativo profundo detectado por análisis textual: requisito estar soltera.', 'deep_textual', 10, 'cold', NULL),
  ('refiere_amigas_conocidas', 'Patrón narrativo profundo detectado por análisis textual: refiere amigas conocidas.', 'deep_textual', 5, 'cold', NULL),
  ('recibir_visitas_en_domicilio', 'Patrón narrativo profundo detectado por análisis textual: recibir visitas en domicilio.', 'deep_textual', 2, 'cold', NULL),
  ('fotografia_corporal', 'Patrón narrativo profundo detectado por análisis textual: fotografia corporal.', 'deep_textual', 1, 'cold', NULL),
  ('pide_firma_pagaré', 'Patrón narrativo profundo detectado por análisis textual: pide firma pagaré.', 'deep_textual', 1, 'cold', NULL),
  ('amenaza_con_deportar', 'Patrón narrativo profundo detectado por análisis textual: amenaza con deportar.', 'deep_textual', 1, 'cold', NULL),
  ('menciona_iglesia_o_grupo_religioso', 'Patrón narrativo profundo detectado por análisis textual: menciona iglesia o grupo religioso.', 'deep_textual', 1, 'cold', NULL),
  ('requisito_ser_menor_de_25', 'Patrón narrativo profundo detectado por análisis textual: requisito ser menor de 25.', 'deep_textual', 1, 'cold', NULL),
  ('adelanto_de_sueldo_primer_dia', 'Patrón narrativo profundo detectado por análisis textual: adelanto de sueldo primer dia.', 'deep_textual', 0, 'cold', NULL),
  ('compra_de_producto_inicial', 'Patrón narrativo profundo detectado por análisis textual: compra de producto inicial.', 'deep_textual', 0, 'cold', NULL),
  ('empresa_recien_creada', 'Patrón narrativo profundo detectado por análisis textual: empresa recien creada.', 'deep_textual', 0, 'cold', NULL),
  ('sueldo_no_mencionado', 'Patrón narrativo profundo detectado por análisis textual: sueldo no mencionado.', 'deep_textual', 0, 'cold', NULL),
  ('horario_noche_exclusivo', 'Patrón narrativo profundo detectado por análisis textual: horario noche exclusivo.', 'deep_textual', 0, 'cold', NULL),
  ('entrevista_por_videollamada_cerrada', 'Patrón narrativo profundo detectado por análisis textual: entrevista por videollamada cerrada.', 'deep_textual', 0, 'cold', NULL),
  ('pago_en_efectivo_exclusivo', 'Patrón narrativo profundo detectado por análisis textual: pago en efectivo exclusivo.', 'deep_textual', 0, 'cold', NULL),
  ('acceso_restringido_a_familia', 'Patrón narrativo profundo detectado por análisis textual: acceso restringido a familia.', 'deep_textual', 0, 'cold', NULL),
  ('internet_laboral_restringido', 'Patrón narrativo profundo detectado por análisis textual: internet laboral restringido.', 'deep_textual', 0, 'cold', NULL),
  ('cuarto\s+compartido\s+con\s+recruiter', 'Patrón narrativo profundo detectado por análisis textual: cuarto\s+compartido\s+con\s+recruiter.', 'deep_textual', 0, 'cold', NULL),
  ('traslado_nocturno', 'Patrón narrativo profundo detectado por análisis textual: traslado nocturno.', 'deep_textual', 0, 'cold', NULL),
  ('pasaporte\s+custodiado', 'Patrón narrativo profundo detectado por análisis textual: pasaporte\s+custodiado.', 'deep_textual', 0, 'cold', NULL),
  ('contrato_en_otro_idioma', 'Patrón narrativo profundo detectado por análisis textual: contrato en otro idioma.', 'deep_textual', 0, 'cold', NULL),
  ('recorrer_ruta_de_prueba', 'Patrón narrativo profundo detectado por análisis textual: recorrer ruta de prueba.', 'deep_textual', 0, 'cold', NULL),
  ('oferta_por_influencer', 'Patrón narrativo profundo detectado por análisis textual: oferta por influencer.', 'deep_textual', 0, 'cold', NULL),
  ('exigencia_de_cambio_nombre', 'Patrón narrativo profundo detectado por análisis textual: exigencia de cambio nombre.', 'deep_textual', 0, 'cold', NULL),
  ('menciona_deuda_traslado', 'Patrón narrativo profundo detectado por análisis textual: menciona deuda traslado.', 'deep_textual', 0, 'cold', NULL),
  ('uso_de_whatsapp_business_falso', 'Patrón narrativo profundo detectado por análisis textual: uso de whatsapp business falso.', 'deep_textual', 0, 'cold', NULL),
  ('publicidad_solo_imagenes', 'Patrón narrativo profundo detectado por análisis textual: publicidad solo imagenes.', 'deep_textual', 0, 'cold', NULL),
  ('promesa_visa_humanitaria', 'Patrón narrativo profundo detectado por análisis textual: promesa visa humanitaria.', 'deep_textual', 0, 'cold', NULL),
  ('oferta_con_acoso_sexual_temprano', 'Patrón narrativo profundo detectado por análisis textual: oferta con acoso sexual temprano.', 'deep_textual', 0, 'cold', NULL),
  ('eliminacion_de_contacto_post_aceptar', 'Patrón narrativo profundo detectado por análisis textual: eliminacion de contacto post aceptar.', 'deep_textual', 0, 'cold', NULL),
  ('rechaza_videollamada', 'Patrón narrativo profundo detectado por análisis textual: rechaza videollamada.', 'deep_textual', 0, 'cold', NULL),
  ('menciona_sueldo_en_dolares_sin_justificar', 'Patrón narrativo profundo detectado por análisis textual: menciona sueldo en dolares sin justificar.', 'deep_textual', 0, 'cold', NULL),
  ('pide_cambio_de_ciudad_rapido', 'Patrón narrativo profundo detectado por análisis textual: pide cambio de ciudad rapido.', 'deep_textual', 0, 'cold', NULL),
  ('menciona_familiar_del_empleador', 'Patrón narrativo profundo detectado por análisis textual: menciona familiar del empleador.', 'deep_textual', 0, 'cold', NULL),
  ('promete_vuelos_pagados', 'Patrón narrativo profundo detectado por análisis textual: promete vuelos pagados.', 'deep_textual', 0, 'cold', NULL),
  ('presión_emocional_madre_sola', 'Patrón narrativo profundo detectado por análisis textual: presión emocional madre sola.', 'deep_textual', 0, 'cold', NULL),
  ('agencia_con_pagina_reciente', 'Patrón narrativo profundo detectado por análisis textual: agencia con pagina reciente.', 'deep_textual', 0, 'cold', NULL),
  ('solicita_referencia_no_verificable', 'Patrón narrativo profundo detectado por análisis textual: solicita referencia no verificable.', 'deep_textual', 0, 'cold', NULL),
  ('reunion_en_hotel', 'Patrón narrativo profundo detectado por análisis textual: reunion en hotel.', 'deep_textual', 0, 'cold', NULL),
  ('reclutador_habla_como_amigo_cercano', 'Patrón narrativo profundo detectado por análisis textual: reclutador habla como amigo cercano.', 'deep_textual', 0, 'cold', NULL),
  ('solicita_fotografía_intima', 'Patrón narrativo profundo detectado por análisis textual: solicita fotografía intima.', 'deep_textual', 0, 'cold', NULL),
  ('menciona_posible_esquema_comisiones_exagerado', 'Patrón narrativo profundo detectado por análisis textual: menciona posible esquema comisiones exagerado.', 'deep_textual', 0, 'cold', NULL),
  ('ofrece_alojamiento_compartido_con_desconocidos', 'Patrón narrativo profundo detectado por análisis textual: ofrece alojamiento compartido con desconocidos.', 'deep_textual', 0, 'cold', NULL),
  ('oferta_con_promesa_de_romance', 'Patrón narrativo profundo detectado por análisis textual: oferta con promesa de romance.', 'deep_textual', 0, 'cold', NULL),
  ('contratacion_sin_entrevista', 'Patrón narrativo profundo detectado por análisis textual: contratacion sin entrevista.', 'deep_textual', 0, 'cold', NULL),
  ('mencion_explicita_de_trata', 'Patrón narrativo profundo detectado por análisis textual: mencion explicita de trata.', 'deep_textual', 0, 'cold', NULL)
ON CONFLICT (pattern_name) DO UPDATE SET
  pattern_description = EXCLUDED.pattern_description,
  observed_count = EXCLUDED.observed_count,
  dominance_bucket = EXCLUDED.dominance_bucket;